name = "atom-clicker"
compatibility_date = "2025-09-25"
compatibility_flags = ["nodejs_compat"]
main = ".svelte-kit/cloudflare/_worker.js"
preview_urls = true
workers_dev = true

[assets]
binding = "ASSETS"
directory = ".svelte-kit/cloudflare"

[observability.logs]
enabled = true
